---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: splunk-config
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-namespaces
  interval: 1m0s
  path: ./splunk-config/
  postBuild:
    substitute:
      splunk_url: ${splunk_url}
      splunk_port: ${splunk_port}
      splunk_token: ${splunk_token}
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
    namespace: tanzu-continuousdelivery-resources