---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-gitops-packages
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-gitops-serviceacct
  interval: 1m0s
  path: ./flux-config/
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
    namespace: tanzu-continuousdelivery-resources