---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-external-dns
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-external-dns-sa
  interval: 1m0s
  path: ./external-dns
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
    namespace: tanzu-continuousdelivery-resources
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: external-dns
  #     namespace: external-dns
