# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: input-resource-reader
#   namespace: vmware-system-tmc
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: input-resource-reader
#   namespace: vmware-system-tmc
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - configmaps
#   verbs:
#   - get
#   - list
#   - watch
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: input-resource-reader
#   namespace: vmware-system-tmc
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: input-resource-reader
# subjects:
# - kind: ServiceAccount
#   name: input-resource-reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: input-resource-reader
  namespace: packages
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: input-resource-reader
subjects:
- kind: ServiceAccount
  name: input-resource-reader

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: splunk-config
  namespace: packages
spec:
  serviceAccountName: input-resource-reader # used to fetch input resources
  inputResources:
  - name: secret
    ref:
      apiVersion: v1
      kind: Secret
      name: splunk-logging
  template:
    #type: generic
    data:
      splunk_host: $(.secret.data.splunk_host)
      splunk_port: $(.secret.data.splunk_port)
      splunk_key: $(.secret.data.splunk_key)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: splunk-config
  namespace: packages
spec:
  toNamespace: '*'

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: splunk-config
  namespace: tanzu-continuousdelivery-resources
spec:
  fromNamespace: packages
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: splunk-config
  namespace: tanzu-continuousdelivery-resources
spec:
  fromNamespace: packages