---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cluster-admin-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cluster-admin-cluster-role-binding
    tkg.tanzu.vmware.com/tanzu-package-Secret: contour-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: pkg-gitops-pkgi-sa
  name: contour
  namespace: packages
spec:
  serviceAccountName: pkg-gitops-pkgi-sa
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.25.2+vmware.1-tkg.1
  values:
  - secretRef:
      name: contour-packages-values
