---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: harbor-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: harbor-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: harbor-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: harbor-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: harbor
  namespace: packages
spec:
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: 2.6.3+vmware.1-tkg.1
  serviceAccountName: harbor-packages-sa
  values:
  - secretRef:
      name: harbor-packages-values
