---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cluster-admin-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cluster-admin-cluster-role-binding
    tkg.tanzu.vmware.com/tanzu-package-Secret: harbor-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: pkg-gitops-pkgi-sa
  name: harbor
  namespace: packages
spec:
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: 2.8.4+vmware.1-tkg.1
  serviceAccountName: pkg-gitops-pkgi-sa
  values:
  - secretRef:
      name: harbor-packages-values
