---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cluster-admin-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cluster-admin-cluster-role-binding
    tkg.tanzu.vmware.com/tanzu-package-Secret: fluent-bit-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: pkg-gitops-pkgi-sa
  name: fluent-bit
  namespace: packages
spec:
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: 2.1.6+vmware.1-tkg.1
  serviceAccountName: pkg-gitops-pkgi-sa
  values:
  - secretRef:
      name: fluent-bit-packages-values
