apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- values-secret.yaml
#- package-install.yaml
#- aws-creds.yml

spec:
  postBuild:
    substitute:
      cluster_name: ${cluster_name}

# secretGenerator:
# - name: external-dns-packages-values
#   namespace: infra-packages
#   files:
#   - values.yml
#   type: Opaque
#   options:
#     annotations:
#       tkg.tanzu.vmware.com/tanzu-package: external-dns-packages