---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: external-dns
  namespace: packages
spec:
  serviceAccountName: externaldns-packages-sa
  packageRef:
    refName: external-dns.tanzu.vmware.com
    versionSelection:
      constraints: 0.13.4+vmware.2-tkg.3
  values:
  - secretRef:
      name: external-dns-packages-values