deployment:
  args:
    - --source=service
    - --source=ingress
    - --provider=aws
    - --aws-assume-role=arn:aws:iam::949667649007:role/svc.external.dns.cdinkens
    - --events
    - --policy=sync
    - --aws-zone-type=public
    - --aws-prefer-cname
    - --registry=txt
    - --txt-owner-id=${cluster_name}-edns
    - --txt-prefix=txt_
    - --zone-id-filter=Z10298972GXWRA0HFV72Y
    - --log-level=info
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: aws_access_key_id
          name: aws-externaldns
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: aws_secret_access_key
          name: aws-externaldns
namespace: external-dns
