apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-packages-sa
  namespace: packages
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-manager-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-manager-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-manager-packages-sa
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: cert-manager
  namespace: packages
spec:
  serviceAccountName: cert-manager-packages-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.2+vmware.1-tkg.1
